## DAY3（数据框DataFrame上）

- 如何创建df
- df基操

`pandas.DataFrame( data, index, columns, dtype, copy)`

DataFrame 是一个表格型的数据结构，它含有一组有序的列，每列可以是不同的值类型（数值、字符串、布尔型值）。DataFrame 既有行索引也有列索引，它可以被看做由 Series 组成的字典（共同用一个索引）。
就当做excel的sheet或者sql的table来看就好，有行有列，也是最常见的数据结构！

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = [['A',10],
        ['B',12],
        ['C',13]]

In [3]:
data = [['A',10],['B',12],['C',13]]
# 这里的['A',10]代表每一行的内容，共有三行
df = pd.DataFrame(data,
                  columns=['第一列','第二列'], 
                  index = ['第一行','第二行','第三行'])
df

第一列  第二列
第一行   A   10
第二行   B   12
第三行   C   13

In [4]:
np.array([[11,22,33],[44,55,66]])

array([[11, 22, 33],
       [44, 55, 66]])

In [5]:
data = np.array([[11,22,33],[44,55,66]])
df = pd.DataFrame(data)
df

0   1   2
0  11  22  33
1  44  55  66

In [6]:
data = {'名字':['小张','小王','小李','小赵'],
        '年龄':[23,22,21,24]}

In [7]:
data = {'名字':['小张','小王','小李','小赵'],
        '年龄':[23,22,21,24]}
df=pd.DataFrame(data)
df

名字  年龄
0  小张  23
1  小王  22
2  小李  21
3  小赵  24

In [8]:
df = pd.DataFrame(np.random.randn(100,4), columns=list('ABCD'))
df

A         B         C         D
0  -0.798889  1.719379  0.399849  0.043246
1   0.732417  0.732514 -0.160320 -2.784795
2   0.109585  0.348132 -1.138820 -0.342442
3   0.731788  0.245670 -0.979054 -0.206748
4  -0.934403 -0.365191  1.047965  1.030607
..       ...       ...       ...       ...
95  1.175548  0.702278  0.010254 -1.308739
96  1.662727 -0.219054 -0.587763 -0.923856
97  0.433886  0.895073 -1.291979  0.470407
98  0.139416 -0.182575  1.342806  3.316543
99  0.842580  1.322592 -0.138481 -0.324096

[100 rows x 4 columns]

In [9]:
df = pd.DataFrame({  'A' : 1.,    
                     # 使用1.代表1.0，用一个浮点数填充整个列
                     'B' : pd.Timestamp('20130102'),
                     # 用时间戳填充整个列
                     'C' : pd.Series([1,2,3,4],index=list(range(4)),dtype='float32'),
                     # 用系列
                     'D' : np.array([3]*4,dtype='int32'),
                     # 用数组
                     'E' : pd.Categorical(["test","train","test","train"]),
                     # 转换为类别变量
                     'F' : 'foo' })
                     # 字符填充
df

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  2.0  3  train  foo
2  1.0 2013-01-02  3.0  3   test  foo
3  1.0 2013-01-02  4.0  3  train  foo

In [10]:
df = pd.DataFrame(np.random.randn(100,4), columns=list('ABCD'))
df

A         B         C         D
0   0.076086 -0.126999  0.096663 -0.951464
1   1.128109 -2.362867  0.788128  1.160285
2  -2.063336  0.261180  0.817255 -0.180902
3  -0.557011 -0.033976  0.023517 -0.924478
4   0.219806  0.057373 -2.680299 -0.710763
..       ...       ...       ...       ...
95  0.129305 -0.220610  1.355726 -0.183141
96  1.701298  0.397630  0.586241  0.110027
97  0.089850  0.102024 -2.188208  0.933951
98 -0.674098  0.566144 -0.750386  1.797855
99 -0.516875 -0.135809 -0.312337  0.523898

[100 rows x 4 columns]

In [11]:
df.head()

A         B         C         D
0  0.076086 -0.126999  0.096663 -0.951464
1  1.128109 -2.362867  0.788128  1.160285
2 -2.063336  0.261180  0.817255 -0.180902
3 -0.557011 -0.033976  0.023517 -0.924478
4  0.219806  0.057373 -2.680299 -0.710763

In [12]:
df.tail()

A         B         C         D
95  0.129305 -0.220610  1.355726 -0.183141
96  1.701298  0.397630  0.586241  0.110027
97  0.089850  0.102024 -2.188208  0.933951
98 -0.674098  0.566144 -0.750386  1.797855
99 -0.516875 -0.135809 -0.312337  0.523898

In [13]:
df.index

RangeIndex(start=0, stop=100, step=1)

In [14]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [15]:
df.values

array([[ 7.60863654e-02, -1.26998856e-01,  9.66634958e-02,
        -9.51464210e-01],
       [ 1.12810889e+00, -2.36286737e+00,  7.88127784e-01,
         1.16028462e+00],
       [-2.06333606e+00,  2.61179707e-01,  8.17254921e-01,
        -1.80902317e-01],
       [-5.57010990e-01, -3.39756470e-02,  2.35168788e-02,
        -9.24478134e-01],
       [ 2.19806444e-01,  5.73726773e-02, -2.68029886e+00,
        -7.10762571e-01],
       [-1.10622192e-01, -1.35959096e+00,  2.48219621e+00,
         1.21543602e+00],
       [ 9.68828924e-01,  1.03498202e+00,  4.22045508e-01,
         1.25379477e+00],
       [-7.67252586e-01, -1.98158969e+00,  1.76843975e-02,
        -1.20189706e+00],
       [ 1.13633106e+00,  6.95225481e-01,  5.14850875e-01,
        -4.40537008e-01],
       [-8.03250786e-01, -3.91670074e-01,  1.54985730e-02,
         1.04110529e-01],
       [-6.83762346e-02, -1.52020804e+00,  1.83689680e+00,
        -1.70009635e+00],
       [-3.94150813e-01, -8.76658495e-01,  1.09808131e+00,
      

In [16]:
df.to_numpy()

array([[ 7.60863654e-02, -1.26998856e-01,  9.66634958e-02,
        -9.51464210e-01],
       [ 1.12810889e+00, -2.36286737e+00,  7.88127784e-01,
         1.16028462e+00],
       [-2.06333606e+00,  2.61179707e-01,  8.17254921e-01,
        -1.80902317e-01],
       [-5.57010990e-01, -3.39756470e-02,  2.35168788e-02,
        -9.24478134e-01],
       [ 2.19806444e-01,  5.73726773e-02, -2.68029886e+00,
        -7.10762571e-01],
       [-1.10622192e-01, -1.35959096e+00,  2.48219621e+00,
         1.21543602e+00],
       [ 9.68828924e-01,  1.03498202e+00,  4.22045508e-01,
         1.25379477e+00],
       [-7.67252586e-01, -1.98158969e+00,  1.76843975e-02,
        -1.20189706e+00],
       [ 1.13633106e+00,  6.95225481e-01,  5.14850875e-01,
        -4.40537008e-01],
       [-8.03250786e-01, -3.91670074e-01,  1.54985730e-02,
         1.04110529e-01],
       [-6.83762346e-02, -1.52020804e+00,  1.83689680e+00,
        -1.70009635e+00],
       [-3.94150813e-01, -8.76658495e-01,  1.09808131e+00,
      

In [17]:
df.describe()

A           B           C           D
count  100.000000  100.000000  100.000000  100.000000
mean     0.108890   -0.092660   -0.045362    0.122022
std      0.831869    1.032841    0.979138    1.010011
min     -2.084374   -2.362867   -2.680299   -2.538351
25%     -0.493714   -0.758418   -0.695650   -0.501369
50%      0.163146   -0.039486   -0.133957    0.165765
75%      0.658131    0.631611    0.566141    0.901069
max      1.893327    2.620564    2.482196    2.353915

In [18]:
df.T

0         1         2         3         4         5         6   \
A  0.076086  1.128109 -2.063336 -0.557011  0.219806 -0.110622  0.968829   
B -0.126999 -2.362867  0.261180 -0.033976  0.057373 -1.359591  1.034982   
C  0.096663  0.788128  0.817255  0.023517 -2.680299  2.482196  0.422046   
D -0.951464  1.160285 -0.180902 -0.924478 -0.710763  1.215436  1.253795   

         7         8         9   ...        90        91        92        93  \
A -0.767253  1.136331 -0.803251  ... -0.213940  0.194616 -0.102082  0.348034   
B -1.981590  0.695225 -0.391670  ...  1.125299 -0.872960  1.029774  1.155892   
C  0.017684  0.514851  0.015499  ... -0.372146 -0.470303 -1.539738 -0.105462   
D -1.201897 -0.440537  0.104111  ...  0.636961  1.028609  0.301315  1.072926   

         94        95        96        97        98        99  
A  0.109765  0.129305  1.701298  0.089850 -0.674098 -0.516875  
B  0.125638 -0.220610  0.397630  0.102024  0.566144 -0.135809  
C -0.656829  1.355726  0.586241 -2.188208 -0.750386 -0.312337  
D -0.440411 -0.183141  0.110027  0.933951  1.797855  0.523898  

[4 rows x 100 columns]

In [19]:
df.columns = ['a','B','c','D']

In [20]:
df

a         B         c         D
0   0.076086 -0.126999  0.096663 -0.951464
1   1.128109 -2.362867  0.788128  1.160285
2  -2.063336  0.261180  0.817255 -0.180902
3  -0.557011 -0.033976  0.023517 -0.924478
4   0.219806  0.057373 -2.680299 -0.710763
..       ...       ...       ...       ...
95  0.129305 -0.220610  1.355726 -0.183141
96  1.701298  0.397630  0.586241  0.110027
97  0.089850  0.102024 -2.188208  0.933951
98 -0.674098  0.566144 -0.750386  1.797855
99 -0.516875 -0.135809 -0.312337  0.523898

[100 rows x 4 columns]

In [21]:
df.sort_index(axis=1, ascending=False, key = lambda x: x.str.lower())

D         c         B         a
0  -0.951464  0.096663 -0.126999  0.076086
1   1.160285  0.788128 -2.362867  1.128109
2  -0.180902  0.817255  0.261180 -2.063336
3  -0.924478  0.023517 -0.033976 -0.557011
4  -0.710763 -2.680299  0.057373  0.219806
..       ...       ...       ...       ...
95 -0.183141  1.355726 -0.220610  0.129305
96  0.110027  0.586241  0.397630  1.701298
97  0.933951 -2.188208  0.102024  0.089850
98  1.797855 -0.750386  0.566144 -0.674098
99  0.523898 -0.312337 -0.135809 -0.516875

[100 rows x 4 columns]

In [22]:
df.columns = ['A','B','C','D']

In [23]:
df.sort_values(by = 1, axis=1)

B         C         A         D
0  -0.126999  0.096663  0.076086 -0.951464
1  -2.362867  0.788128  1.128109  1.160285
2   0.261180  0.817255 -2.063336 -0.180902
3  -0.033976  0.023517 -0.557011 -0.924478
4   0.057373 -2.680299  0.219806 -0.710763
..       ...       ...       ...       ...
95 -0.220610  1.355726  0.129305 -0.183141
96  0.397630  0.586241  1.701298  0.110027
97  0.102024 -2.188208  0.089850  0.933951
98  0.566144 -0.750386 -0.674098  1.797855
99 -0.135809 -0.312337 -0.516875  0.523898

[100 rows x 4 columns]

In [24]:
df.sort_values(by = 1, axis=1, key = lambda x: abs(x))

C         A         D         B
0   0.096663  0.076086 -0.951464 -0.126999
1   0.788128  1.128109  1.160285 -2.362867
2   0.817255 -2.063336 -0.180902  0.261180
3   0.023517 -0.557011 -0.924478 -0.033976
4  -2.680299  0.219806 -0.710763  0.057373
..       ...       ...       ...       ...
95  1.355726  0.129305 -0.183141 -0.220610
96  0.586241  1.701298  0.110027  0.397630
97 -2.188208  0.089850  0.933951  0.102024
98 -0.750386 -0.674098  1.797855  0.566144
99 -0.312337 -0.516875  0.523898 -0.135809

[100 rows x 4 columns]

## 习题

1. 创建一个10行4列的随机整数数矩阵（叫df）（-10到10）（np.random.randint），列名为a、B、c、D（使用split），行索引为20220101开始的每五天（每隔四天）的timestamp。(seed=2022)

In [25]:
import pandas as pd
import numpy as np

In [26]:
np.random.seed(2022)
df = pd.DataFrame(
        data = np.random.randint(-10,10+1,size = [100,4]),
        columns = 'a B c D'.split(),
        # columns = ['a','B','c','D']
        # columns = list('aBcD')
        index = pd.date_range(start = '20220101',
                              periods = 100,
                              freq = '4D')
)

In [27]:
df

a   B   c   D
2022-01-01  3   6   7   7
2022-01-05  6   8   6  -1
2022-01-09 -9   1   9  -2
2022-01-13  1   6   9  -4
2022-01-17 -2   4   6   1
...        ..  ..  ..  ..
2023-01-16 -4   0   3  10
2023-01-20  3   2  -4   2
2023-01-24  2   1   5   9
2023-01-28  8  -5  10   4
2023-02-01  4 -10   4  -1

[100 rows x 4 columns]

In [28]:
case1 = np.array([['A',2],['B',3]])
case2 = [['A',2],['B',3]]
case3 = {'A':2,'B':3}
case4 = pd.Series([['A',2],['B',3]])

In [29]:
pd.Series([1,2,3,4],index = list('abcd')).to_frame()

0
a  1
b  2
c  3
d  4

In [30]:
type(pd.Series([1,2,3,4],index = list('abcd')).to_frame())

pandas.core.frame.DataFrame

2. 对上面的df做以下操作（不得改变原数据，不得make copy）：
  1. 关于列名从大到小排序（忽略大小写）
  2. 再接着，对c这一列的值的平方进行排倒序，如果平局对D列继续排序，然后是a，最后是B
  3. 最后忽略掉行index的变化

In [31]:
df.sort_index(axis=1,ascending = False, key = lambda x: x.str.lower())\
.sort_values(by = ['c','D','a','B'], axis=0, ascending = False, key = lambda x: x**2).set_index(df.index)

D   c   B  a
2022-01-01  9 -10  -2 -2
2022-01-05 -8 -10   6  7
2022-01-09 -7  10  10 -5
2022-01-13  4  10  -5  8
2022-01-17 -2 -10   2  0
...        ..  ..  .. ..
2023-01-16  9   0  -7  7
2023-01-20 -2   0  -9  6
2023-01-24 -2   0   7  4
2023-01-28  2   0 -10 -1
2023-02-01  1   0  -7 -9

[100 rows x 4 columns]

3. 写一个函数view_df
  1. 输入为df和sort_by
    1. df
    2. sort_by指的是根据某个列进行排序（正序）
  2. 输出为此df的前4行和后4行合在一起（pd.concat）

  带入第一题的df，如果对view_df(df）的结果关于不同的列的值进行排序（正序），请统计一下排序后第一行数据对应的时间是在上半个月（该日期在15号之前）的case的个数【答案是3】（是的，故意在难为大家，自己梳理梳理分解一下）

In [32]:
def view_df(df, sort_by = 'B'):
    return pd.concat([df.head(4),df.tail(4)])\
                .sort_values(by = sort_by)

In [33]:
cnt = 0
for col in df.columns:
    if ((view_df(df, sort_by = col).index[0].day)<15):
        cnt+=1
        # cnt = cnt+1

In [34]:
cnt

3