## DAY3（数据框DataFrame上）

- 如何创建df
- df基操

`pandas.DataFrame( data, index, columns, dtype, copy)`

DataFrame 是一个表格型的数据结构，它含有一组有序的列，每列可以是不同的值类型（数值、字符串、布尔型值）。DataFrame 既有行索引也有列索引，它可以被看做由 Series 组成的字典（共同用一个索引）。
就当做excel的sheet或者sql的table来看就好，有行有列，也是最常见的数据结构！

In [6]:
import pandas as pd
import numpy as np

In [7]:
data = [['A',10],
        ['B',12],
        ['C',13]]

In [8]:
data = [['A',10],['B',12],['C',13]]
# 这里的['A',10]代表每一行的内容，共有三行
df = pd.DataFrame(data,
                  columns=['第一列','第二列'], 
                  index = ['第一行','第二行','第三行'])
df

第一列  第二列
第一行   A   10
第二行   B   12
第三行   C   13

In [11]:
np.array([[11,22,33],[44,55,66]])

array([[11, 22, 33],
       [44, 55, 66]])

In [3]:
data = np.array([[11,22,33],[44,55,66]])
df = pd.DataFrame(data)
df

0   1   2
0  11  22  33
1  44  55  66

In [12]:
data = {'名字':['小张','小王','小李','小赵'],
        '年龄':[23,22,21,24]}

In [4]:
data = {'名字':['小张','小王','小李','小赵'],
        '年龄':[23,22,21,24]}
df=pd.DataFrame(data)
df

名字  年龄
0  小张  23
1  小王  22
2  小李  21
3  小赵  24

In [16]:
df = pd.DataFrame(np.random.randn(100,4), columns=list('ABCD'))
df

A         B         C         D
0  -0.204847  1.362250  2.248861 -0.087904
1  -0.195379 -0.728094  0.405476  0.096266
2  -1.612209 -1.912672 -1.764975 -0.307226
3  -0.008886 -0.729317 -0.309159 -0.404772
4  -0.506621  0.815165 -0.535957  0.126149
..       ...       ...       ...       ...
95  0.745685 -0.551097  0.813275  0.650597
96 -0.656548  0.518599  0.391767 -0.432524
97 -0.520914  1.601559  1.306306  0.299631
98  0.348073  1.852337 -0.130801  1.720337
99  0.522563 -1.771250  0.891338  0.833723

[100 rows x 4 columns]

In [18]:
df = pd.DataFrame({  'A' : 1.,    
                     # 使用1.代表1.0，用一个浮点数填充整个列
                     'B' : pd.Timestamp('20130102'),
                     # 用时间戳填充整个列
                     'C' : pd.Series([1,2,3,4],index=list(range(4)),dtype='float32'),
                     # 用系列
                     'D' : np.array([3]*4,dtype='int32'),
                     # 用数组
                     'E' : pd.Categorical(["test","train","test","train"]),
                     # 转换为类别变量
                     'F' : 'foo' })
                     # 字符填充
df

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  2.0  3  train  foo
2  1.0 2013-01-02  3.0  3   test  foo
3  1.0 2013-01-02  4.0  3  train  foo

In [26]:
df = pd.DataFrame(np.random.randn(100,4), columns=list('ABCD'))
df

A         B         C         D
0  -0.184678  0.175040 -2.134440  0.109561
1   0.420003  0.131141 -1.357080 -0.848362
2  -0.805069  0.198811  1.129412 -0.905888
3   0.844412  1.611422  0.770718  1.042945
4   1.119666 -0.254929  0.337672  0.689507
..       ...       ...       ...       ...
95  0.723530 -0.159281 -1.438188 -0.608657
96  0.467257  0.402648 -0.452367  0.347611
97  1.591035 -0.818421 -0.157088  1.496493
98  0.531323 -1.195636  0.366143  0.012103
99 -1.422232 -0.266266 -1.013829  1.950344

[100 rows x 4 columns]

In [27]:
df.head()

A         B         C         D
0 -0.184678  0.175040 -2.134440  0.109561
1  0.420003  0.131141 -1.357080 -0.848362
2 -0.805069  0.198811  1.129412 -0.905888
3  0.844412  1.611422  0.770718  1.042945
4  1.119666 -0.254929  0.337672  0.689507

In [28]:
df.tail()

A         B         C         D
95  0.723530 -0.159281 -1.438188 -0.608657
96  0.467257  0.402648 -0.452367  0.347611
97  1.591035 -0.818421 -0.157088  1.496493
98  0.531323 -1.195636  0.366143  0.012103
99 -1.422232 -0.266266 -1.013829  1.950344

In [29]:
df.index

RangeIndex(start=0, stop=100, step=1)

In [9]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [30]:
df.values

array([[-0.1846782 ,  0.17504031, -2.13443962,  0.10956133],
       [ 0.42000296,  0.13114138, -1.35708034, -0.84836186],
       [-0.80506857,  0.19881119,  1.12941227, -0.90588767],
       [ 0.84441191,  1.61142212,  0.77071758,  1.04294477],
       [ 1.11966583, -0.25492858,  0.33767203,  0.68950682],
       [-0.8976088 ,  0.53921029, -0.37457423,  0.25400787],
       [ 0.31006012,  0.24562097,  0.15598879,  0.15507496],
       [-1.35200891,  0.33864734,  0.67898918, -0.93727709],
       [-0.62126171, -1.08528866, -0.53367878,  1.25211957],
       [-1.47734895,  0.57108262, -0.94574833,  0.41116438],
       [ 0.59491172, -0.14780226, -0.8149876 ,  1.79697142],
       [-1.13645422, -0.9291553 ,  1.50607583,  0.69386617],
       [-0.89577791,  0.4280865 , -0.73850251, -0.01182225],
       [ 1.03326161, -0.18138849,  0.58876247,  0.41089651],
       [ 0.62663578, -0.87620017,  1.35265256, -0.67992183],
       [ 0.22065831,  0.60538854,  1.63509301, -0.5838637 ],
       [ 0.25678209,  0.

In [31]:
df.to_numpy()

array([[-0.1846782 ,  0.17504031, -2.13443962,  0.10956133],
       [ 0.42000296,  0.13114138, -1.35708034, -0.84836186],
       [-0.80506857,  0.19881119,  1.12941227, -0.90588767],
       [ 0.84441191,  1.61142212,  0.77071758,  1.04294477],
       [ 1.11966583, -0.25492858,  0.33767203,  0.68950682],
       [-0.8976088 ,  0.53921029, -0.37457423,  0.25400787],
       [ 0.31006012,  0.24562097,  0.15598879,  0.15507496],
       [-1.35200891,  0.33864734,  0.67898918, -0.93727709],
       [-0.62126171, -1.08528866, -0.53367878,  1.25211957],
       [-1.47734895,  0.57108262, -0.94574833,  0.41116438],
       [ 0.59491172, -0.14780226, -0.8149876 ,  1.79697142],
       [-1.13645422, -0.9291553 ,  1.50607583,  0.69386617],
       [-0.89577791,  0.4280865 , -0.73850251, -0.01182225],
       [ 1.03326161, -0.18138849,  0.58876247,  0.41089651],
       [ 0.62663578, -0.87620017,  1.35265256, -0.67992183],
       [ 0.22065831,  0.60538854,  1.63509301, -0.5838637 ],
       [ 0.25678209,  0.

In [12]:
df.describe()

A           B           C           D
count  100.000000  100.000000  100.000000  100.000000
mean    -0.037357   -0.156330   -0.048157    0.004772
std      1.169692    1.092030    1.059902    0.976548
min     -2.910543   -2.642297   -2.519962   -1.983765
25%     -0.913198   -0.685573   -0.648775   -0.595886
50%     -0.098147   -0.219149   -0.047594    0.013169
75%      0.695333    0.474067    0.578417    0.562648
max      3.479813    3.356829    3.116607    2.635545

In [13]:
df.T

0         1         2         3         4         5         6   \
A  2.119025  2.163053  0.608507 -0.805249 -0.977325 -0.105672  0.799635   
B -0.639141 -0.972635  0.185513 -2.216506 -0.250679  0.187289 -0.005181   
C  0.239870  0.356271 -1.070570  0.237003 -0.349436 -0.589115  2.904038   
D -0.051092 -0.057491  1.007069 -0.292817 -0.494257  0.419766 -1.217387   

         7         8         9   ...        90        91        92        93  \
A  1.004797 -2.910543  0.092668  ... -1.138247 -0.892953  0.726396 -2.067440   
B -0.120574 -0.464356 -0.217452  ...  0.986711 -0.938321  0.537291 -1.271665   
C -1.652211 -0.253875 -0.800411  ...  0.305644  1.572707 -0.935663 -1.113595   
D -1.210724  1.301783  2.101312  ... -1.462965  0.589362 -0.537173 -1.929711   

         94        95        96        97        98        99  
A  0.243256 -1.534976 -0.764858  0.490673 -0.728555  0.165681  
B  0.706547  0.472669 -0.261254 -0.672964 -0.002539 -1.582530  
C  0.298259 -0.078407  0.854734 -0.697727  0.167988  1.065394  
D  1.129605 -1.236833 -0.577687  0.502411  1.078904  1.049249  

[4 rows x 100 columns]

In [47]:
df.columns = ['a','B','c','D']

In [48]:
df

a         B         c         D
0  -0.184678  0.175040 -2.134440  0.109561
1   0.420003  0.131141 -1.357080 -0.848362
2  -0.805069  0.198811  1.129412 -0.905888
3   0.844412  1.611422  0.770718  1.042945
4   1.119666 -0.254929  0.337672  0.689507
..       ...       ...       ...       ...
95  0.723530 -0.159281 -1.438188 -0.608657
96  0.467257  0.402648 -0.452367  0.347611
97  1.591035 -0.818421 -0.157088  1.496493
98  0.531323 -1.195636  0.366143  0.012103
99 -1.422232 -0.266266 -1.013829  1.950344

[100 rows x 4 columns]

In [52]:
df.sort_index(axis=1, ascending=False, key = lambda x: x.str.lower())

D         c         B         a
0   0.109561 -2.134440  0.175040 -0.184678
1  -0.848362 -1.357080  0.131141  0.420003
2  -0.905888  1.129412  0.198811 -0.805069
3   1.042945  0.770718  1.611422  0.844412
4   0.689507  0.337672 -0.254929  1.119666
..       ...       ...       ...       ...
95 -0.608657 -1.438188 -0.159281  0.723530
96  0.347611 -0.452367  0.402648  0.467257
97  1.496493 -0.157088 -0.818421  1.591035
98  0.012103  0.366143 -1.195636  0.531323
99  1.950344 -1.013829 -0.266266 -1.422232

[100 rows x 4 columns]

In [54]:
df.columns = ['A','B','C','D']

In [60]:
df.sort_values(by = 1, axis=1)

C         D         B         A
0  -2.134440  0.109561  0.175040 -0.184678
1  -1.357080 -0.848362  0.131141  0.420003
2   1.129412 -0.905888  0.198811 -0.805069
3   0.770718  1.042945  1.611422  0.844412
4   0.337672  0.689507 -0.254929  1.119666
..       ...       ...       ...       ...
95 -1.438188 -0.608657 -0.159281  0.723530
96 -0.452367  0.347611  0.402648  0.467257
97 -0.157088  1.496493 -0.818421  1.591035
98  0.366143  0.012103 -1.195636  0.531323
99 -1.013829  1.950344 -0.266266 -1.422232

[100 rows x 4 columns]

In [62]:
df.sort_values(by = 1, axis=1, key = lambda x: abs(x))

B         A         D         C
0   0.175040 -0.184678  0.109561 -2.134440
1   0.131141  0.420003 -0.848362 -1.357080
2   0.198811 -0.805069 -0.905888  1.129412
3   1.611422  0.844412  1.042945  0.770718
4  -0.254929  1.119666  0.689507  0.337672
..       ...       ...       ...       ...
95 -0.159281  0.723530 -0.608657 -1.438188
96  0.402648  0.467257  0.347611 -0.452367
97 -0.818421  1.591035  1.496493 -0.157088
98 -1.195636  0.531323  0.012103  0.366143
99 -0.266266 -1.422232  1.950344 -1.013829

[100 rows x 4 columns]